spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://user:8080
        predicates:
        - Path=/user/**
#logging:
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40c{1.} [%X{user}] :